{{- with .Values.serviceAccount }}
{{- if .create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes.serviceAccountName" . }}
  labels:
    {{- include "kubernetes.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- end }}
