apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-app.fullname" . }}-config
  labels:
    {{- include "backend-app.labels" . | nindent 4 }}
data:
  FLASK_ENV: "production"
  CORS_ORIGINS: "http://localhost:3000,http://localhost:5173"
  DATABASE_URL: "sqlite:///cat_ecommerce.db"
  SQLALCHEMY_ECHO: "False"
